### ISSUE TITLE
I got error

### ISSUE THREAD

**Issue by nvnnghia** [afunTW/pyqt5-binary-classifier#1]
Thanks for sharing, Please help, i got this error:

`python main.py --img-dir 001/ 
  File "main.py", line 28
    app.exec()
           ^
SyntaxError: invalid syntax`

**Comment by afunTW** [comment]
@nvnnghia thanks. that's my honor to see my tool does help someone else

app.exec just an entry to build up a pyqt5 application, could you please to show more environment information?
Moreover, I do provide the Pipfile for pipenv, recommand you to use that.

**Comment by nvnnghia** [comment]
Thank you, The problem is app.exec_().

**Comment by afunTW** [comment]
Yes. For more information about pyqt5 exec refer to [stackoverflow](https://stackoverflow.com/questions/22610720/should-i-use-app-exec-or-app-exec-in-my-pyqt-application)
